### ISSUE TITLE
klipper Z_TILT_ADJUST

### ISSUE THREAD

**Issue by Raabi91** [markniu/Bed_Distance_sensor#18]
no_stop_probe ist not working with klipper and Z_TILT_ADJUST after the first run it goes into shutdown

`Internal error on command:"Z_TILT_ADJUST"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 198, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 135, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/z_tilt.py", line 145, in cmd_Z_TILT_ADJUST
    self.probe_helper.start_probe(gcmd)
  File "/home/pi/klipper/klippy/extras/probe.py", line 484, in start_probe
    done = self._move_next()
  File "/home/pi/klipper/klippy/extras/probe.py", line 421, in _move_next
    (probe.mcu_probe.results[i]/100.0)
IndexError: list index out of range`

is it possible to activate no_stop_probe only for bed mesh

**Comment by Raabi91** [comment]
is done
